Added hrut support to lowo and wothin. Rationalised wothin. Added xopp support to szerk.

diff --git a/lowo b/lowo
--- a/lowo
+++ b/lowo
@@ -2,29 +2,49 @@
 # 2018-01-13
 # Lots Of Webpages Opener (lowo)
 # Use as: lowo <filename> , where <filename> is without extension. Opens webpages in ~/.lowo/<filename>.txt .
+# Accepts the -p option for only opening with a probability read from hrut.
 # Lines starting with # are ignored.
 # Url's to open must start the line with "http" in the file; any comments to display can come after a space.
 # Any other line is displayed and paused.
+# Added hrut integration [2021-06-20 Sun]
 
-if [[ $# == 1 ]] ; then
-
- ffront=${1%.*}
- file=$HOME/.lowo/$ffront.txt
-
- if [ ! -f $file ] ; then
-  echo "Can't find the file $file."
-  exit
+if [[ $# == 1 ]]
+then
+ rawfname="$1"
+elif [[ $# == 2 ]] 
+then
+ if [[ "$1" == "-p" ]]
+ then
+  rawfname="$2"
+ else
+  echo "Usage: lowo <filename> or lowo -p <filename>"
+  exit 1
  fi
-
 else
-  echo "Usage: lowo <filename>"
-  exit
+ echo "Usage: lowo <filename>"
+ exit 1
+fi
+
+ffront=${rawfname%.*}
+file=$HOME/.lowo/$ffront.txt
+
+if [ ! -f $file ] ; then
+ echo "Can't find the file $file."
+ exit
 fi
 
 nol=$(cat $file | wc -l)
 
 for i in `seq 1 $nol`;
 do
+ if [[ -f ~/.hrut/hrut.pkl ]] && [[ "$1" == "-p" ]]
+ then
+  yesno=$(hrut -p)
+  if [[ "$yesno" == "0" ]]
+  then
+   continue
+  fi
+ fi
  line=$(sed -n "$i p" $file) 
  url=${line%% *}
  cmt=${line#* }
